In [1]:
import pandas as pd

In [24]:
%%time

df = pd.read_excel('data/entry-clearance-visa-outcomes-datasets-sep-2019.xlsx', sheet_name='Data - Vis_D02')

CPU times: user 49.1 s, sys: 815 ms, total: 49.9 s
Wall time: 51.8 s

In [3]:
!pip install xlrd

Collecting xlrd
  Using cached xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
Installing collected packages: xlrd
Successfully installed xlrd-1.2.0

In [40]:
!pip install pycountry

Collecting pycountry
  Downloading pycountry-19.8.18.tar.gz (10.0 MB)
     |████████████████████████████████| 10.0 MB 7.7 MB/s eta 0:00:01    |█████████████████▉              | 5.6 MB 4.0 MB/s eta 0:00:02
Building wheels for collected packages: pycountry
  Building wheel for pycountry (setup.py) ... done
  Created wheel for pycountry: filename=pycountry-19.8.18-py2.py3-none-any.whl size=10627360 sha256=6c9e68140577bcc24050db06cefb0d6f4d62d8f02a932697a2a96387db58368c
  Stored in directory: /Users/campea/Library/Caches/pip/wheels/00/77/65/5f318c3c30b046b450a385ecfc690125f8a270cdb0f3f483b4
Successfully built pycountry
Installing collected packages: pycountry
Successfully installed pycountry-19.8.18

In [216]:
import pycountry

In [220]:
pycountry.ExistingCountries

pycountry.ExistingCountries

In [ ]:
['Africa North',
'Africa Sub-Saharan']

In [ ]:
['Africa North',
'Africa Sub-Saharan']

In [227]:
(df['Region'] == 'Africa North') | (df['Region'] == 'Africa Sub-Saharan')

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...
278557     True
278558     True
278559     True
278560     True
278561     True
278562     True
278563     True
278564     True
278565     True
278566     True
278567     True
278568     True
278569     True
278570     True
278571     True
278572     True
278573     True
278574     True
278575     True
278576     True
278577     True
278578     True
278579     True
278580     True
278581     True
278582     True
278583     True
278584     True
278585     True
278586     True
Name: Region, Length: 278587, dtype: bool

In [237]:
df[(df['Year'] == 2018) & ((df['Region'] != 'Africa North') & (df['Region'] != 'Africa Sub-Saharan'))].groupby('Case outcome').sum()

                  Year  Decisions
Case outcome
Issued        14991722    2538006
Lapsed           76684         48
Refused        7531176     237620
Withdrawn      2558824       6259

In [240]:
1-2538006/(48+30+237620+6259+2538006)

0.08769239562136522

In [245]:
(1-135960/(135960+364003+2221+37))/(1-2538006/(48+30+237620+6259+2538006))

8.316371355206977

In [143]:
def from_country_to_code(name):
    try:
        return pycountry.countries.get(name=name).alpha_3
    except AttributeError:
        
        return missing_countries.get(name, "")

In [204]:
all_codes = [{'country_code': x.alpha_3, 'Nationality': '', 'Decisions':0, 'Region': ''} for x in pycountry.countries.objects]

In [205]:
all_codes

[{'country_code': 'ABW', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'AFG', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'AGO', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'AIA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ALA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ALB', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'AND', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ARE', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ARG', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ARM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ASM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ATA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ATF', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ATG', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'AUS', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'AUT', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'AZE', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BDI', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BEL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BEN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BES', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BFA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BGD', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BGR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BHR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BHS', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BIH', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BLM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BLR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BLZ', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BMU', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BOL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BRA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BRB', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BRN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BTN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BVT', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'BWA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CAF', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CAN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CCK', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CHE', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CHL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CHN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CIV', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CMR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'COD', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'COG', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'COK', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'COL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'COM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CPV', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CRI', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CUB', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CUW', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CXR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CYM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CYP', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'CZE', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'DEU', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'DJI', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'DMA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'DNK', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'DOM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'DZA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ECU', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'EGY', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ERI', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ESH', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ESP', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'EST', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ETH', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'FIN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'FJI', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'FLK', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'FRA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'FRO', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'FSM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GAB', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GBR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GEO', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GGY', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GHA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GIB', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GIN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GLP', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GMB', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GNB', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GNQ', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GRC', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GRD', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GRL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GTM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GUF', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GUM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'GUY', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'HKG', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'HMD', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'HND', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'HRV', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'HTI', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'HUN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'IDN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'IMN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'IND', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'IOT', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'IRL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'IRN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'IRQ', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ISL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ISR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ITA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'JAM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'JEY', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'JOR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'JPN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'KAZ', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'KEN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'KGZ', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'KHM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'KIR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'KNA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'KOR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'KWT', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'LAO', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'LBN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'LBR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'LBY', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'LCA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'LIE', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'LKA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'LSO', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'LTU', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'LUX', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'LVA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MAC', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MAF', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MAR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MCO', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MDA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MDG', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MDV', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MEX', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MHL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MKD', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MLI', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MLT', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MMR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MNE', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MNG', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MNP', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MOZ', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MRT', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MSR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MTQ', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MUS', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MWI', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MYS', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'MYT', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'NAM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'NCL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'NER', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'NFK', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'NGA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'NIC', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'NIU', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'NLD', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'NOR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'NPL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'NRU', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'NZL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'OMN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'PAK', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'PAN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'PCN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'PER', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'PHL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'PLW', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'PNG', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'POL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'PRI', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'PRK', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'PRT', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'PRY', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'PSE', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'PYF', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'QAT', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'REU', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ROU', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'RUS', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'RWA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SAU', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SDN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SEN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SGP', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SGS', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SHN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SJM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SLB', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SLE', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SLV', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SMR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SOM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SPM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SRB', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SSD', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'STP', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SUR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SVK', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SVN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SWE', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SWZ', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SXM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SYC', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'SYR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TCA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TCD', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TGO', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'THA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TJK', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TKL', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TKM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TLS', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TON', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TTO', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TUN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TUR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TUV', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TWN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'TZA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'UGA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'UKR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'UMI', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'URY', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'USA', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'UZB', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'VAT', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'VCT', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'VEN', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'VGB', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'VIR', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'VNM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'VUT', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'WLF', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'WSM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'YEM', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ZAF', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ZMB', 'Nationality': '', 'Decisions': 0, 'Region': ''},
 {'country_code': 'ZWE', 'Nationality': '', 'Decisions': 0, 'Region': ''}]

In [190]:
x = pycountry.countries.objects[0]

In [145]:
from_country_to_code('Bolivia')

'BOL'

In [156]:
pycountry.countries.search_fuzzy('Congo')

[Country(alpha_2='CG', alpha_3='COG', name='Congo', numeric='178', official_name='Republic of the Congo'),
 Country(alpha_2='CD', alpha_3='COD', name='Congo, The Democratic Republic of the', numeric='180')]

In [157]:
missing_countries = {
     'Bahamas, The': 'BHS',
     'Bolivia': 'BOL',
     'Brunei': 'BRN',
     'Burkina': 'BFA',
     'Burma': 'MMR',
     'Cape Verde': 'CPV',
     'Congo (Democratic Republic)': 'COD',
     'Czech Republic': 'CZE',
     'Gambia, The': 'GMB',
     'Iran': 'IRN',
     'Ivory Coast': 'CIV',
     'Korea (North)': 'PRK',
     'Korea (South)': 'KOR',
     'Laos': 'LAO',
     'Macau': 'MAC',
     'Macedonia': 'MKD',
     'Moldova': 'MDA',
     'Occupied Palestinian Territories': 'PS',
     'Russia': 'RUS',
     'Serbia and Montenegro': 'SRB',
     'St. Kitts and Nevis': 'KNA',
     'St. Lucia': 'LCA',
     'St. Vincent and the Grenadines': 'VCT',
     'Surinam': 'SUR',
     'Swaziland': 'Eswatini',
     'Syria': 'SYR',
     'Taiwan': 'TWN',
     'Tanzania': 'TZA',
     'Vatican City': 'VAT',
     'Venezuela': 'VEN',
     'Vietnam': 'VNM',
     'Anguilla (British)': 'AIA',
     'Bermuda (British)': 'BMU',
     'Pitcairn Islands (British)': 'PCN',
     'Cayman Islands (British)': 'CYM',
     'Gibraltar (British)': 'GIB',
     'St. Helena (British)': '',
     'Turks and Caicos Islands (British)': 'TCA',
     'Montserrat (British)': 'MSR',
     'Former Yugoslavia': 'SHN',
     'Micronesia': 'FSM',
     'East Timor': 'TLS',
     'Kosovo': 'SRB',
     'Virgin Islands (British)': 'VGB',
     'Sudan (South)': 'SSD',
     'Cyprus (Northern part of)': 'CYP'}

In [150]:
froodf[df['country_code'] == '']['Nationality'].unique()[1]

'Bolivia'

In [193]:
{name: from_country_to_code(name) for name in df[df['country_code'] == '']['Nationality'].unique()}

{'British overseas citizens': '',
 'Other and unknown': '',
 'Refugee': '',
 'Stateless': '',
 'St. Helena (British)': ''}

In [192]:
df['country_code'].unique()

array(['AFG', 'ALB', 'DZA', 'AGO', 'ATG', 'ARG', 'ARM', 'AUS', 'AZE',
       'BHS', 'BHR', 'BGD', 'BRB', 'BLR', 'BLZ', 'BEN', 'BTN', 'BOL',
       'BIH', 'BWA', 'BRA', '', 'BRN', 'BGR', 'BFA', 'MMR', 'BDI', 'KHM',
       'CMR', 'CAN', 'CPV', 'CAF', 'TCD', 'CHL', 'CHN', 'COL', 'COM',
       'COG', 'COD', 'CRI', 'HRV', 'CUB', 'CYP', 'CZE', 'DNK', 'DJI',
       'DMA', 'DOM', 'ECU', 'EGY', 'SLV', 'GNQ', 'ERI', 'EST', 'ETH',
       'FJI', 'FIN', 'FRA', 'GAB', 'GMB', 'GEO', 'DEU', 'GHA', 'GRD',
       'GTM', 'GIN', 'GNB', 'GUY', 'HTI', 'HND', 'HKG', 'HUN', 'ISL',
       'IND', 'IDN', 'IRN', 'IRQ', 'ISR', 'CIV', 'JAM', 'JPN', 'JOR',
       'KAZ', 'KEN', 'KIR', 'PRK', 'KOR', 'KWT', 'KGZ', 'LAO', 'LVA',
       'LBN', 'LSO', 'LBR', 'LBY', 'LTU', 'MAC', 'MKD', 'MDG', 'MWI',
       'MYS', 'MDV', 'MLI', 'MLT', 'MHL', 'MRT', 'MUS', 'MEX', 'MDA',
       'MNG', 'MAR', 'MOZ', 'NAM', 'NPL', 'NLD', 'NZL', 'NIC', 'NER',
       'NGA', 'PS', 'OMN', 'PAK', 'PAN', 'PNG', 'PRY', 'PER', 'PHL',
       'POL', 'QAT', 'ROU', 'RUS', 'RWA', 'WSM', 'STP', 'SAU', 'SEN',
       'SRB', 'SYC', 'SLE', 'SGP', 'SVK', 'SLB', 'SOM', 'ZAF', 'ESP',
       'LKA', 'KNA', 'LCA', 'VCT', 'SDN', 'SUR', 'Eswatini', 'SWE', 'CHE',
       'SYR', 'TWN', 'TJK', 'TZA', 'THA', 'TGO', 'TON', 'TTO', 'TUN',
       'TUR', 'TKM', 'UGA', 'UKR', 'ARE', 'USA', 'URY', 'UZB', 'VAT',
       'VEN', 'VNM', 'YEM', 'ZMB', 'ZWE', 'AIA', 'BMU', 'IRL', 'NOR',
       'PCN', 'SMR', 'SVN', 'VUT', 'AND', 'AUT', 'CYM', 'GIB', 'ITA',
       'TUV', 'MCO', 'PRT', 'BEL', 'NRU', 'GRC', 'NIU', 'TCA', 'MSR',
       'SHN', 'FSM', 'TLS', 'MNE', 'LIE', 'LUX', 'VGB', 'SSD'],
      dtype=object)

In [195]:
df['country_code'] = df['Nationality'].apply(from_country_to_code)

In [196]:
df.to_csv('data/final_visa_data.csv', index=0)

In [52]:
pd.read_csv('final_visa_data.csv')

,Year,Quarter,Nationality,Region,Visa type group,Visa type,Visa type subgroup,Applicant type,Case outcome,Decisions,country_code
0,2005,2005 Q1,Afghanistan,Asia Central,Dep. joining or accompanying,Dep. joining or accompanying,Joining or accompanying: Child,Dependant,Issued,87,AFG
1,2005,2005 Q1,Afghanistan,Asia Central,Dep. joining or accompanying,Dep. joining or accompanying,Joining or accompanying: Child,Dependant,Refused,17,AFG
2,2005,2005 Q1,Afghanistan,Asia Central,Dep. joining or accompanying,Dep. joining or accompanying,Joining or accompanying: Partner,Dependant,Withdrawn,1,AFG
3,2005,2005 Q1,Afghanistan,Asia Central,Family,Family,Family: Child (for immediate settlement),All,Issued,2,AFG
4,2005,2005 Q1,Afghanistan,Asia Central,Family,Family,Family: Child (for immediate settlement),All,Refused,4,AFG
5,2005,2005 Q1,Afghanistan,Asia Central,Family,Family,Family: Other,All,Issued,205,AFG
6,2005,2005 Q1,Afghanistan,Asia Central,Family,Family,Family: Other,All,Refused,33,AFG
7,2005,2005 Q1,Afghanistan,Asia Central,Family,Family,Family: Other,All,Lapsed,4,AFG
8,2005,2005 Q1,Afghanistan,Asia Central,Family,Family,Family: Other (for immediate settlement),All,Issued,5,AFG
9,2005,2005 Q1,Afghanistan,Asia Central,Family,Family,Family: Other (for immediate settlement),All,Refused,23,AFG
10,2005,2005 Q1,Afghanistan,Asia Central,Family,Family,Family: Partner,All,Issued,103,AFG
11,2005,2005 Q1,Afghanistan,Asia Central,Family,Family,Family: Partner,All,Refused,21,AFG
12,2005,2005 Q1,Afghanistan,Asia Central,Family,Family,Family: Partner,All,Withdrawn,1,AFG
13,2005,2005 Q1,Afghanistan,Asia Central,Family,Family,Family: Partner (for immediate settlement),All,Issued,1,AFG
14,2005,2005 Q1,Afghanistan,Asia Central,Family,Family,Family: Partner (for immediate settlement),All,Refused,1,AFG
15,2005,2005 Q1,Afghanistan,Asia Central,Other,Other settlement visas,Other settlement (indefinite leave),All,Issued,8,AFG
16,2005,2005 Q1,Afghanistan,Asia Central,Other,Other temporary visas,EEA family permits,All,Issued,45,AFG
17,2005,2005 Q1,Afghanistan,Asia Central,Other,Other temporary visas,EEA family permits,All,Refused,1,AFG
18,2005,2005 Q1,Afghanistan,Asia Central,Other,Other temporary visas,Other temporary,All,Refused,1,AFG
19,2005,2005 Q1,Afghanistan,Asia Central,Other,Other temporary visas,Transit,All,Issued,52,AFG
20,2005,2005 Q1,Afghanistan,Asia Central,Other,Other temporary visas,Transit,All,Refused,3,AFG
21,2005,2005 Q1,Afghanistan,Asia Central,Other,Other temporary visas,Visitors,Main applicant,Issued,360,AFG
22,2005,2005 Q1,Afghanistan,Asia Central,Other,Other temporary visas,Visitors,Main applicant,Refused,119,AFG
23,2005,2005 Q1,Afghanistan,Asia Central,Other,Other temporary visas,Visitors,Main applicant,Withdrawn,5,AFG
24,2005,2005 Q1,Afghanistan,Asia Central,Other,Other temporary visas,Visitors,Main applicant,Lapsed,2,AFG
25,2005,2005 Q1,Afghanistan,Asia Central,Study,Non-PBS study,Students,Dependant,Refused,1,AFG
26,2005,2005 Q1,Afghanistan,Asia Central,Study,Non-PBS study,Students,Main applicant,Issued,8,AFG
27,2005,2005 Q1,Afghanistan,Asia Central,Study,Non-PBS study,Students,Main applicant,Refused,17,AFG
28,2005,2005 Q1,Afghanistan,Asia Central,Study,Non-PBS study,Students,Main applicant,Withdrawn,1,AFG
29,2005,2005 Q1,Afghanistan,Asia Central,Work,Non-PBS work,Work Permit Holders,Main applicant,Issued,1,AFG
...,...,...,...,...,...,...,...,...,...,...,...
278557,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Study,Non-PBS study,Short-term study (previously Student Visitors),Main applicant,Issued,37,ZWE
278558,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Study,Non-PBS study,Short-term study (previously Student Visitors),Main applicant,Refused,3,ZWE
278559,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - General student,Dependant,Issued,10,ZWE
278560,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - General student,Dependant,Refused,3,ZWE
278561,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - Child student,Main applicant,Issued,10,ZWE
278562,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - General student,Main applicant,Issued,334,ZWE
278563,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - General student,Main applicant,Refused,14,ZWE
278564,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Non-PBS work,Start-up,Dependant,Issued,1,ZWE
278565,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Non-PBS work,Work Permit Holders,Dependant,Issued,5,ZWE
278566,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Non-PBS work,Domestic workers in Private Households,Main applicant,Issued,3,ZWE
278567,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Non-PBS work,Domestic workers in Private Households,Main applicant,Refused,2,ZWE
278568,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Non-PBS work,Start-up,Main applicant,Issued,1,ZWE
278569,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Non-PBS work,UK Ancestry,Main applicant,Issued,45,ZWE
278570,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Non-PBS work,UK Ancestry,Main applicant,Refused,7,ZWE
278571,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Non-PBS work,Work Permit Holders,Main applicant,Issued,5,ZWE
278572,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 1 (High value),Tier 1 - Exceptional Talent,Dependant,Issued,4,ZWE
278573,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 1 (High value),Tier 1 - General,Dependant,Withdrawn,1,ZWE
278574,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Issued,140,ZWE
278575,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Refused,17,ZWE
278576,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Intra Company Transfers Long Term,Dependant,Issued,1,ZWE
278577,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Issued,139,ZWE
278578,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Refused,5,ZWE
278579,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Intra Company Transfers Long Term,Main applicant,Issued,1,ZWE
278580,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 5 (Youth mobility and temporary worker),Tier 5 - Charity Workers,Main applicant,Issued,4,ZWE
278581,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 5 (Youth mobility and temporary worker),Tier 5 - Charity Workers,Main applicant,Refused,2,ZWE
278582,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 5 (Youth mobility and temporary worker),Tier 5 - Creative and Sporting,Main applicant,Issued,18,ZWE
278583,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 5 (Youth mobility and temporary worker),Tier 5 - Creative and Sporting,Main applicant,Refused,9,ZWE
278584,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 5 (Youth mobility and temporary worker),Tier 5 - Creative and Sporting,Main applicant,Withdrawn,3,ZWE
278585,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 5 (Youth mobility and temporary worker),Tier 5 - Government Authorised Exchange,Main applicant,Issued,3,ZWE
278586,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 5 (Youth mobility and temporary worker),Tier 5 - Religious Workers,Main applicant,Issued,2,ZWE

In [15]:
df[(df['Visa type '] == 'Tier 2 (Skilled)') | (df['Visa type '] == 'Tier 4 (Sponsored study)')]

,Year,Quarter,Nationality,Region,Visa type group,Visa type,Visa type subgroup,Applicant type,Case outcome,Decisions
65732,2008,2008 Q4,Australia,Oceania,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Issued,1
66249,2008,2008 Q4,Canada,America North,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Refused,1
66509,2008,2008 Q4,Croatia,EU Other,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Refused,1
66669,2008,2008 Q4,Egypt,Africa North,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Issued,1
66955,2008,2008 Q4,Ghana,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Issued,2
66956,2008,2008 Q4,Ghana,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Refused,1
67213,2008,2008 Q4,India,Asia South,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Issued,8
67214,2008,2008 Q4,India,Asia South,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Issued,1
67215,2008,2008 Q4,India,Asia South,Work,Tier 2 (Skilled),Tier 2 - Intra Company Transfers,Main applicant,Issued,32
67216,2008,2008 Q4,India,Asia South,Work,Tier 2 (Skilled),Tier 2 - Intra Company Transfers,Main applicant,Refused,2
67537,2008,2008 Q4,Japan,Asia East,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Issued,1
67538,2008,2008 Q4,Japan,Asia East,Work,Tier 2 (Skilled),Tier 2 - Intra Company Transfers,Main applicant,Issued,6
67870,2008,2008 Q4,Libya,Africa North,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Issued,5
68004,2008,2008 Q4,Malaysia,Asia South East,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Issued,1
68073,2008,2008 Q4,Mauritius,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Issued,1
68074,2008,2008 Q4,Mauritius,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Intra Company Transfers,Main applicant,Issued,1
68107,2008,2008 Q4,Mexico,America Central and South,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Refused,1
68216,2008,2008 Q4,Morocco,Africa North,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Issued,1
68451,2008,2008 Q4,Nigeria,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Refused,1
68452,2008,2008 Q4,Nigeria,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Withdrawn,1
68453,2008,2008 Q4,Nigeria,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Ministers of Religion,Main applicant,Refused,1
68644,2008,2008 Q4,Pakistan,Asia South,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Issued,3
68645,2008,2008 Q4,Pakistan,Asia South,Work,Tier 2 (Skilled),Tier 2 - Intra Company Transfers,Main applicant,Issued,1
68646,2008,2008 Q4,Pakistan,Asia South,Work,Tier 2 (Skilled),Tier 2 - Ministers of Religion,Main applicant,Refused,1
68693,2008,2008 Q4,Peru,America Central and South,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Refused,1
68760,2008,2008 Q4,Philippines,Asia South East,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Refused,15
69194,2008,2008 Q4,South Africa,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Issued,1
69195,2008,2008 Q4,South Africa,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Refused,2
69196,2008,2008 Q4,South Africa,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Issued,4
69197,2008,2008 Q4,South Africa,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Refused,2
...,...,...,...,...,...,...,...,...,...,...
278473,2019,2019 Q3,Yemen,Middle East,Study,Tier 4 (Sponsored study),Tier 4 - Child student,Main applicant,Issued,2
278474,2019,2019 Q3,Yemen,Middle East,Study,Tier 4 (Sponsored study),Tier 4 - Child student,Main applicant,Refused,1
278475,2019,2019 Q3,Yemen,Middle East,Study,Tier 4 (Sponsored study),Tier 4 - General student,Main applicant,Issued,67
278476,2019,2019 Q3,Yemen,Middle East,Study,Tier 4 (Sponsored study),Tier 4 - General student,Main applicant,Refused,8
278480,2019,2019 Q3,Yemen,Middle East,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Issued,14
278481,2019,2019 Q3,Yemen,Middle East,Work,Tier 2 (Skilled),Tier 2 - Intra Company Transfers Long Term,Dependant,Issued,4
278482,2019,2019 Q3,Yemen,Middle East,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Issued,2
278483,2019,2019 Q3,Yemen,Middle East,Work,Tier 2 (Skilled),Tier 2 - Intra Company Transfers Long Term,Main applicant,Issued,2
278508,2019,2019 Q3,Zambia,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - General student,Dependant,Issued,18
278509,2019,2019 Q3,Zambia,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - General student,Dependant,Refused,4
278510,2019,2019 Q3,Zambia,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - Child student,Main applicant,Issued,4
278511,2019,2019 Q3,Zambia,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - General student,Main applicant,Issued,192
278512,2019,2019 Q3,Zambia,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - General student,Main applicant,Refused,3
278516,2019,2019 Q3,Zambia,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Issued,13
278517,2019,2019 Q3,Zambia,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Refused,1
278518,2019,2019 Q3,Zambia,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Issued,10
278519,2019,2019 Q3,Zambia,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Intra Company Transfers,Main applicant,Issued,1
278520,2019,2019 Q3,Zambia,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Intra Company Transfers Long Term,Main applicant,Issued,2
278521,2019,2019 Q3,Zambia,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Ministers of Religion,Main applicant,Refused,1
278559,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - General student,Dependant,Issued,10
278560,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - General student,Dependant,Refused,3
278561,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - Child student,Main applicant,Issued,10
278562,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - General student,Main applicant,Issued,334
278563,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Study,Tier 4 (Sponsored study),Tier 4 - General student,Main applicant,Refused,14
278574,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Issued,140
278575,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Dependant,Dependant,Refused,17
278576,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Intra Company Transfers Long Term,Dependant,Issued,1
278577,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Issued,139
278578,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - General,Main applicant,Refused,5
278579,2019,2019 Q3,Zimbabwe,Africa Sub-Saharan,Work,Tier 2 (Skilled),Tier 2 - Intra Company Transfers Long Term,Main applicant,Issued,1

In [213]:
gp = df[(df['Year'] == 2011) & (df['Visa type group'] == 'Study') & (df['Case outcome'] == 'Issued')].append(pd.DataFrame(all_codes),sort=False).groupby(by='country_code').agg(
    {
        'Decisions': sum,
        'Region': 'first',
        'Nationality': 'first'
    }
)

In [214]:
gp

,Decisions,Region,Nationality
country_code,,,
,132,Other,British overseas citizens
ABW,0,,
AFG,421,Asia Central,Afghanistan
AGO,442,Africa Sub-Saharan,Angola
AIA,0,,
ALA,0,,
ALB,375,Europe Other,Albania
AND,1,Europe Other,Andorra
ARE,1650,Middle East,United Arab Emirates
ARG,108,America Central and South,Argentina
ARM,252,Europe Other,Armenia
ASM,0,,
ATA,0,,
ATF,0,,
ATG,10,America Central and South,Antigua and Barbuda
AUS,1239,Oceania,Australia
AUT,0,,
AZE,790,Europe Other,Azerbaijan
BDI,12,Africa Sub-Saharan,Burundi
BEL,0,,
BEN,32,Africa Sub-Saharan,Benin
BES,0,,
BFA,21,Africa Sub-Saharan,Burkina
BGD,6633,Asia South,Bangladesh
BGR,0,,
BHR,788,Middle East,Bahrain
BHS,58,America Central and South,"Bahamas, The"
BIH,127,Europe Other,Bosnia and Herzegovina
BLM,0,,
BLR,433,Europe Other,Belarus
...,...,...,...
TJK,75,Asia Central,Tajikistan
TKL,0,,
TKM,159,Asia Central,Turkmenistan
TLS,8,Asia South East,East Timor
TON,6,Oceania,Tonga
TTO,365,America Central and South,Trinidad and Tobago
TUN,251,Africa North,Tunisia
TUR,11402,Europe Other,Turkey
TUV,0,,
TWN,3577,Asia East,Taiwan
TZA,610,Africa Sub-Saharan,Tanzania
UGA,542,Africa Sub-Saharan,Uganda
UKR,2573,Europe Other,Ukraine
UMI,0,,
URY,31,America Central and South,Uruguay
USA,14644,America North,United States
UZB,214,Asia Central,Uzbekistan
VAT,0,,
VCT,28,America Central and South,St. Vincent and the Grenadines
VEN,488,America Central and South,Venezuela
VGB,0,,
VIR,0,,
VNM,3421,Asia South East,Vietnam
VUT,1,Oceania,Vanuatu
WLF,0,,
WSM,1,Oceania,Samoa
YEM,201,Middle East,Yemen
ZAF,700,Africa Sub-Saharan,South Africa
ZMB,313,Africa Sub-Saharan,Zambia
ZWE,331,Africa Sub-Saharan,Zimbabwe

In [212]:
gp.append(pd.DataFrame(all_codes), sort=False).groupby(by='country_code').agg(
    {'Decisions': 'sum', 'Region': 'first', 'Nationality': 'first'})

,Decisions,Region,Nationality
country_code,,,
,132,Other,British overseas citizens
ABW,0,,
AFG,421,Asia Central,Afghanistan
AGO,442,Africa Sub-Saharan,Angola
AIA,0,,
ALA,0,,
ALB,375,Europe Other,Albania
AND,1,Europe Other,Andorra
ARE,1650,Middle East,United Arab Emirates
ARG,108,America Central and South,Argentina
ARM,252,Europe Other,Armenia
ASM,0,,
ATA,0,,
ATF,0,,
ATG,10,America Central and South,Antigua and Barbuda
AUS,1239,Oceania,Australia
AUT,0,,
AZE,790,Europe Other,Azerbaijan
BDI,12,Africa Sub-Saharan,Burundi
BEL,0,,
BEN,32,Africa Sub-Saharan,Benin
BES,0,,
BFA,21,Africa Sub-Saharan,Burkina
BGD,6633,Asia South,Bangladesh
BGR,0,,
BHR,788,Middle East,Bahrain
BHS,58,America Central and South,"Bahamas, The"
BIH,127,Europe Other,Bosnia and Herzegovina
BLM,0,,
BLR,433,Europe Other,Belarus
...,...,...,...
TJK,75,Asia Central,Tajikistan
TKL,0,,
TKM,159,Asia Central,Turkmenistan
TLS,8,Asia South East,East Timor
TON,6,Oceania,Tonga
TTO,365,America Central and South,Trinidad and Tobago
TUN,251,Africa North,Tunisia
TUR,11402,Europe Other,Turkey
TUV,0,,
TWN,3577,Asia East,Taiwan
TZA,610,Africa Sub-Saharan,Tanzania
UGA,542,Africa Sub-Saharan,Uganda
UKR,2573,Europe Other,Ukraine
UMI,0,,
URY,31,America Central and South,Uruguay
USA,14644,America North,United States
UZB,214,Asia Central,Uzbekistan
VAT,0,,
VCT,28,America Central and South,St. Vincent and the Grenadines
VEN,488,America Central and South,Venezuela
VGB,0,,
VIR,0,,
VNM,3421,Asia South East,Vietnam
VUT,1,Oceania,Vanuatu
WLF,0,,
WSM,1,Oceania,Samoa
YEM,201,Middle East,Yemen
ZAF,700,Africa Sub-Saharan,South Africa
ZMB,313,Africa Sub-Saharan,Zambia
ZWE,331,Africa Sub-Saharan,Zimbabwe

In [203]:
gp.head()

       Country  Total Geographical Region country_code
0  Afghanistan    421        Asia Central          AFG
1      Albania    375        Europe Other          ALB
2      Algeria    630        Africa North          DZA
3      Andorra      1        Europe Other          AND
4       Angola    442  Africa Sub-Saharan          AGO

In [208]:
gp.reset_index(inplace=True)

In [200]:
gp.rename({'Nationality': 'Country', 'Decisions': 'Total', 'Region': 'Geographical Region'}, axis=1, inplace=True)

In [68]:
gp.to_json(orient='split')

'{"columns":["Country","Total","Geographical Region","country_code"],"index":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169],"data":[["Afghanistan",421,"Asia Central","AFG"],["Albania",375,"Europe Other","ALB"],["Algeria",630,"Africa North","DZA"],["Andorra",1,"Europe Other","AND"],["Angola",442,"Africa Sub-Saharan","AGO"],["Antigua and Barbuda",10,"America Central and South","ATG"],["Argentina",108,"America Central and South","ARG"],["Armenia",252,"Europe Other","ARM"],["Australia",1239,"Oceania","AUS"],["Azerbaijan",790,"Europe Other","AZE"],["Bahamas, The",58,"America Central and South",""],["Bahrain",788,"Middle East","BHR"],["Bangladesh",6633,"Asia South","BGD"],["Barbados",106,"America Central and South","BRB"],["Belarus",433,"Europe Other","BLR"],["Belize",20,"America Central and South","BLZ"],["Benin",32,"Africa Sub-Saharan","BEN"],["Bermuda (British)",2,"Other",""],["Bhutan",29,"Asia South","BTN"],["Bolivia",54,"America Central and South",""],["Bosnia and Herzegovina",127,"Europe Other","BIH"],["Botswana",230,"Africa Sub-Saharan","BWA"],["Brazil",1938,"America Central and South","BRA"],["British overseas citizens",12,"Other",""],["Brunei",1215,"Asia South East",""],["Burkina",21,"Africa Sub-Saharan",""],["Burma",237,"Asia South East",""],["Burundi",12,"Africa Sub-Saharan","BDI"],["Cambodia",47,"Asia South East","KHM"],["Cameroon",924,"Africa Sub-Saharan","CMR"],["Canada",3540,"America North","CAN"],["Cape Verde",4,"Africa Sub-Saharan",""],["Central African Republic",3,"Africa Sub-Saharan","CAF"],["Chad",7,"Africa Sub-Saharan","TCD"],["Chile",571,"America Central and South","CHL"],["China",59919,"Asia East","CHN"],["Colombia",3971,"America Central and South","COL"],["Comoros",3,"Africa Sub-Saharan","COM"],["Congo",28,"Africa Sub-Saharan","COG"],["Congo (Democratic Republic)",48,"Africa Sub-Saharan",""],["Costa Rica",41,"America Central and South","CRI"],["Croatia",146,"EU Other","HRV"],["Cuba",27,"America Central and South","CUB"],["Cyprus",17,"EU Other","CYP"],["Djibouti",15,"Africa Sub-Saharan","DJI"],["Dominica",18,"America Central and South","DMA"],["Dominican Republic",40,"America Central and South","DOM"],["East Timor",8,"Asia South East",""],["Ecuador",239,"America Central and South","ECU"],["Egypt",1303,"Africa North","EGY"],["El Salvador",16,"America Central and South","SLV"],["Equatorial Guinea",50,"Africa Sub-Saharan","GNQ"],["Eritrea",16,"Africa Sub-Saharan","ERI"],["Ethiopia",211,"Africa Sub-Saharan","ETH"],["Fiji",10,"Oceania","FJI"],["Former Yugoslavia",9,"Europe Other",""],["Gabon",33,"Africa Sub-Saharan","GAB"],["Gambia, The",161,"Africa Sub-Saharan",""],["Georgia",598,"Europe Other","GEO"],["Ghana",1380,"Africa Sub-Saharan","GHA"],["Grenada",25,"America Central and South","GRD"],["Guatemala",22,"America Central and South","GTM"],["Guinea",56,"Africa Sub-Saharan","GIN"],["Guinea-Bissau",2,"Africa Sub-Saharan","GNB"],["Guyana",43,"America Central and South","GUY"],["Haiti",6,"America Central and South","HTI"],["Honduras",12,"America Central and South","HND"],["Hong Kong",7652,"Asia East","HKG"],["India",38558,"Asia South","IND"],["Indonesia",1674,"Asia South East","IDN"],["Iran",2983,"Middle East",""],["Iraq",2592,"Middle East","IRQ"],["Ireland",1,"EU 14","IRL"],["Israel",195,"Middle East","ISR"],["Italy",1,"EU 14","ITA"],["Ivory Coast",110,"Africa Sub-Saharan",""],["Jamaica",132,"America Central and South","JAM"],["Japan",4176,"Asia East","JPN"],["Jordan",1202,"Middle East","JOR"],["Kazakhstan",3072,"Asia Central","KAZ"],["Kenya",1201,"Africa Sub-Saharan","KEN"],["Korea (North)",1,"Asia East",""],["Korea (South)",6435,"Asia East",""],["Kosovo",159,"Europe Other",""],["Kuwait",2168,"Middle East","KWT"],["Kyrgyzstan",137,"Asia Central","KGZ"],["Laos",17,"Asia South East",""],["Lebanon",560,"Middle East","LBN"],["Lesotho",7,"Africa Sub-Saharan","LSO"],["Liberia",40,"Africa Sub-Saharan","LBR"],["Libya",1049,"Africa North","LBY"],["Macau",180,"Asia East",""],["Macedonia",141,"Europe Other",""],["Madagascar",16,"Africa Sub-Saharan","MDG"],["Malawi",227,"Africa Sub-Saharan","MWI"],["Malaysia",7444,"Asia South East","MYS"],["Maldives",86,"Asia South","MDV"],["Mali",34,"Africa Sub-Saharan","MLI"],["Mauritania",45,"Africa North","MRT"],["Mauritius",623,"Africa Sub-Saharan","MUS"],["Mexico",1205,"America Central and South","MEX"],["Moldova",124,"Europe Other",""],["Monaco",7,"Europe Other","MCO"],["Mongolia",175,"Asia East","MNG"],["Montenegro",130,"Europe Other","MNE"],["Morocco",887,"Africa North","MAR"],["Mozambique",38,"Africa Sub-Saharan","MOZ"],["Namibia",49,"Africa Sub-Saharan","NAM"],["Nepal",2880,"Asia South","NPL"],["New Zealand",250,"Oceania","NZL"],["Nicaragua",10,"America Central and South","NIC"],["Niger",14,"Africa Sub-Saharan","NER"],["Nigeria",14613,"Africa Sub-Saharan","NGA"],["Occupied Palestinian Territories",338,"Middle East",""],["Oman",1358,"Middle East","OMN"],["Other and unknown",79,"Other",""],["Pakistan",36099,"Asia South","PAK"],["Panama",16,"America Central and South","PAN"],["Papua New Guinea",8,"Oceania","PNG"],["Paraguay",14,"America Central and South","PRY"],["Peru",408,"America Central and South","PER"],["Philippines",1746,"Asia South East","PHL"],["Poland",1,"EU 8","POL"],["Qatar",1940,"Middle East","QAT"],["Refugee",25,"Other",""],["Romania",1,"EU 2","ROU"],["Russia",13790,"Europe Other",""],["Rwanda",81,"Africa Sub-Saharan","RWA"],["Samoa",1,"Oceania","WSM"],["San Marino",2,"Europe Other","SMR"],["Saudi Arabia",16321,"Middle East","SAU"],["Senegal",127,"Africa Sub-Saharan","SEN"],["Serbia",524,"Europe Other","SRB"],["Seychelles",41,"Africa Sub-Saharan","SYC"],["Sierra Leone",122,"Africa Sub-Saharan","SLE"],["Singapore",2429,"Asia South East","SGP"],["Solomon Islands",1,"Oceania","SLB"],["Somalia",4,"Africa Sub-Saharan","SOM"],["South Africa",700,"Africa Sub-Saharan","ZAF"],["Sri Lanka",5051,"Asia South","LKA"],["St. Kitts and Nevis",18,"America Central and South",""],["St. Lucia",30,"America Central and South",""],["St. Vincent and the Grenadines",28,"America Central and South",""],["Stateless",16,"Other",""],["Sudan",398,"Africa North","SDN"],["Surinam",1,"America Central and South",""],["Swaziland",11,"Africa Sub-Saharan",""],["Syria",700,"Middle East",""],["Taiwan",3577,"Asia East",""],["Tajikistan",75,"Asia Central","TJK"],["Tanzania",610,"Africa Sub-Saharan",""],["Thailand",6890,"Asia South East","THA"],["Togo",19,"Africa Sub-Saharan","TGO"],["Tonga",6,"Oceania","TON"],["Trinidad and Tobago",365,"America Central and South","TTO"],["Tunisia",251,"Africa North","TUN"],["Turkey",11402,"Europe Other","TUR"],["Turkmenistan",159,"Asia Central","TKM"],["Uganda",542,"Africa Sub-Saharan","UGA"],["Ukraine",2573,"Europe Other","UKR"],["United Arab Emirates",1650,"Middle East","ARE"],["United States",14644,"America North","USA"],["Uruguay",31,"America Central and South","URY"],["Uzbekistan",214,"Asia Central","UZB"],["Vanuatu",1,"Oceania","VUT"],["Venezuela",488,"America Central and South",""],["Vietnam",3421,"Asia South East",""],["Yemen",201,"Middle East","YEM"],["Zambia",313,"Africa Sub-Saharan","ZMB"],["Zimbabwe",331,"Africa Sub-Saharan","ZWE"]]}'

In [63]:
gp.head()

   Nationality  Decisions              Region country_code
0  Afghanistan        421        Asia Central          AFG
1      Albania        375        Europe Other          ALB
2      Algeria        630        Africa North          DZA
3      Andorra          1        Europe Other          AND
4       Angola        442  Africa Sub-Saharan          AGO

In [29]:
df['Year'] == 2011)

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...
278557    False
278558    False
278559    False
278560    False
278561    False
278562    False
278563    False
278564    False
278565    False
278566    False
278567    False
278568    False
278569    False
278570    False
278571    False
278572    False
278573    False
278574    False
278575    False
278576    False
278577    False
278578    False
278579    False
278580    False
278581    False
278582    False
278583    False
278584    False
278585    False
278586    False
Name: Year, Length: 278587, dtype: bool

In [9]:
df['Nationality'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British overseas citizens', 'Brunei', 'Bulgaria', 'Burkina',
       'Burma', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo', 'Congo (Democratic Republic)', 'Costa Rica',
       'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia, The',
       'Georgia', 'Germany', 'Ghana', 'Grenada', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong',
       'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
       'Israel', 'Ivory Coast', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Korea (North)',
       'Korea (South)', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia',
       'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Macau',
       'Macedonia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
       'Mexico', 'Moldova', 'Mongolia', 'Morocco', 'Mozambique',
       'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'Occupied Palestinian Territories', 'Oman',
       'Other and unknown', 'Pakistan', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Qatar', 'Refugee',
       'Romania', 'Russia', 'Rwanda', 'Samoa', 'Sao Tome and Principe',
       'Saudi Arabia', 'Senegal', 'Serbia and Montenegro', 'Seychelles',
       'Sierra Leone', 'Singapore', 'Slovakia', 'Solomon Islands',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka',
       'St. Kitts and Nevis', 'St. Lucia',
       'St. Vincent and the Grenadines', 'Stateless', 'Sudan', 'Surinam',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Uganda', 'Ukraine', 'United Arab Emirates', 'United States',
       'Uruguay', 'Uzbekistan', 'Vatican City', 'Venezuela', 'Vietnam',
       'Yemen', 'Zambia', 'Zimbabwe', 'Anguilla (British)',
       'Bermuda (British)', 'Ireland', 'Norway',
       'Pitcairn Islands (British)', 'San Marino', 'Slovenia', 'Vanuatu',
       'Andorra', 'Austria', 'Cayman Islands (British)',
       'Gibraltar (British)', 'Italy', 'Tuvalu', 'Monaco', 'Portugal',
       'Belgium', 'Nauru', 'Greece', 'Niue', 'St. Helena (British)',
       'Turks and Caicos Islands (British)', 'Montserrat (British)',
       'Former Yugoslavia', 'Micronesia', 'East Timor', 'Kosovo',
       'Montenegro', 'Serbia', 'Liechtenstein', 'Luxembourg',
       'Virgin Islands (British)', 'Sudan (South)',
       'Cyprus (Northern part of)'], dtype=object)